import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ShopItem from '../components/ShopItem'
import { Grid, NextUIProvider } from '@nextui-org/react';
import { Button, Text } from '@nextui-org/react';
import HeaderBarSpace from '../components/HeaderBarSpace';
import HeaderBar from '../components/HeaderBar';
import { useRouter } from 'next/router'
import { useEffect } from 'react';

function Home({data}) {
  const router = useRouter();

  useEffect(() => {
    //router.go(-1);
    router.push('./shop');
  })

  return (
    <NextUIProvider>
      <div className={styles.container}>
        <Head>
          <title>Punk Shop</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
  		    <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet"/>
        </Head>

      </div>
    </NextUIProvider>
  )
}

export async function getStaticProps() {
  // const name = "Monke"
  // const price = 34.99
  // const img = "../public/monke.jpeg";
  console.log("ran here");
  const data = {
      title: "Monke", 
      price: 'Ξ 4200',
      img: "/punk2890.png"
  }
  return {
      props: {
          data,
      }
  }
}

export default Home